export declare const INFERENCE_PROVIDER_OPENAI_COMPAT: "openai_compat";
export declare const INFERENCE_PROVIDER_ANTHROPIC: "anthropic";
export declare const INFERENCE_PROVIDER_CODEX_OAUTH: "codex_oauth";
export declare const INFERENCE_PROVIDER_IDS: readonly ["openai_compat", "anthropic", "codex_oauth"];
export type InferenceProviderId = (typeof INFERENCE_PROVIDER_IDS)[number];
export declare function isInferenceProviderId(v: unknown): v is InferenceProviderId;
export declare const DEFAULT_INFERENCE_PROVIDER: InferenceProviderId;
export declare const WEB_PROVIDER_TAVILY: "tavily";
export declare const WEB_PROVIDER_IDS: readonly ["tavily"];
export type WebProviderId = (typeof WEB_PROVIDER_IDS)[number];
export declare function isWebProviderId(v: unknown): v is WebProviderId;
export declare const DEFAULT_WEB_PROVIDER: WebProviderId;
export declare const DEFAULT_PROFILE_ID: "default";
export declare const DEFAULT_PROFILE_NAME: "Default";
export declare const OPENAI_COMPAT_DEFAULT_BASE_URL: "https://api.openai.com/v1";
export declare const OPENAI_COMPAT_DEFAULT_MODEL: "gpt-5";
export declare const OPENAI_COMPAT_DEFAULT_AUTH_HEADER: "Authorization";
export declare const ANTHROPIC_DEFAULT_BASE_URL: "https://api.anthropic.com";
export declare const ANTHROPIC_DEFAULT_MODEL: "claude-sonnet-4-6";
export declare const ANTHROPIC_DEFAULT_AUTH_HEADER: "x-api-key";
export declare const ANTHROPIC_DEFAULT_VERSION: "2023-06-01";
export declare const CODEX_OAUTH_DEFAULT_MODEL: "gpt-5.3-codex";
